# Generated by Django 5.2.6 on 2025-12-16 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_badge_rewardsledger_streak_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('user', 'name', 'year', 'month')},
        ),
    ]
